version: '3.3'
services:
    master:
        image: chrislusf/seaweedfs:dev # use a remote dev image
        ports:
            - 9333:9333
            - 19333:19333
        command: "master -ip=master"
    volume:
        image: chrislusf/seaweedfs:dev # use a remote dev image
        ports:
            - 8080:8080
            - 18080:18080
        command: 'volume -mserver="master:9333" -port=8080 -ip=volume'
        depends_on:
        - master
    filer:
        image: chrislusf/seaweedfs:dev # use a remote dev image
        ports:
            - 8888:8888
            - 18888:18888
        command: 'filer -master="master:9333"'
        depends_on:
            - master
            - volume
    s3:
        image: chrislusf/seaweedfs:dev # use a remote dev image
        ports:
            - 8333:8333
        command: 's3 -filer="filer:8888"'
        depends_on:
            - master
            - volume
            - filer
    webdav:
        image: chrislusf/seaweedfs:dev # use a remote dev image
        ports:
            - 7333:7333
        command: 'webdav -filer="filer:8888"'
        depends_on:
            - master
            - volume
            - filer
    # ssdb:
    #     ports:
    #         - '8888:8888'
    #     image: leobuskin/ssdb-docker:latest
    kvrocks:
        ports:
            - '6666:6666'
        image: kvrocks/kvrocks:latest
    redis:
        # command: redis-server /data/redis-server/redis.conf
        # volumes:
            # - ./redis.conf:/data/redis-server/redis.conf
        ports:
            - '6379:6379'
        image: redislabs/redismod:latest
        # expose:
        #     - '6379'
    # cluster:
    #     ports:
    #         - '7000-7005:7000-7005'
    #     image: grokzen/redis-cluster:latest
    # envoy:
    #     ports:
    #         - '9999:9999'
    #         - '6969:6969'
    #         - '10000:10000'
    #     volumes:
    #         - ./envoy.yaml:/etc/envoy/envoy.yaml
    #     image: envoyproxy/envoy:v1.18-latest
    #     depends_on:
    #         - cluster
    #     links:
    #         - cluster