version: '2'

services:
  kvrocks:
    ports:
        - '6666:6666'
    image: kvrocks/kvrocks:latest
    # volumes:
    #     - ./kvrocks.conf:/kvrocks/conf/kvrocks.conf
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
    command: "master -ip=master -ip.bind=0.0.0.0"
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325'
    depends_on:
      - master