version: '2'
services:
    cassandra:
        container_name: cassandra
        ports:
            - '9042:9042'
        volumes:
            - ./cassdata:/var/lib/cassandra
            - ./cassscripts:/scripts
        image: cassandra
    redis:
        container_name: redis
        ports:
            - '6379:6379'
        command: /usr/local/etc/redis/redis.conf
        volumes:
            - ./redisdata:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        image: redislabs/redismod