version: '3.3'
services:
    postgres:
        container_name: postgres
        ports:
            - '5500:5432'
        environment:
            - POSTGRES_PASSWORD=test
        volumes:
            - './pgdata:/var/lib/postgresql/data'
            - './rc_files:/root'
        image: postgres
    pgadmin:
        container_name: pgadmin
        depends_on:
            - postgres
        ports:
            - '80:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=noob@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=password
        volumes:
            - ./admin:/var/lib/pgadmin
        image: dpage/pgadmin4:latest


# IMPORTANT REF
# https://pgtune.leopard.in.ua/#/
# https://medium.com/swlh/postgresql-replication-with-docker-c6a904becf77

# IMPORTANT INFO
# postgres password is test
# puser password is test
# (theres point in stealing this script kiddies lol)
