version: '3.3'
services:
    postgres:
        container_name: postgres
        ports:
            - '5500:5432'
        environment:
            - POSTGRES_PASSWORD=test
        volumes:
            - './pgdata:/var/lib/postgresql/data'
            - './rc_files:/root'
        image: postgres
    pgadmin:
        container_name: pgadmin
        depends_on:
            - postgres
        ports:
            - '80:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=noob@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=password
        volumes:
            - ./pgadmin4.db:/var/lib/pgadmin/pgadmin4.db
        image: dpage/pgadmin4:latest


# IMPORTANT REF
# https://pgtune.leopard.in.ua/#/
# https://medium.com/swlh/postgresql-replication-with-docker-c6a904becf77

# IMPORTANT INFO

# postgresql: username is postgres password is test
# postgresql: username is puser password is test

# pgadmin4: username is noob@gmail.com AND password is password